### ISSUE TITLE
Using Ginkgo on a cell by bin matrix

### ISSUE THREAD

**Issue by pedrofale** [robertaboukhalil/ginkgo#29]
I would like to use Ginkgo to call copy numbers from data obtained with the 10X Genomics CNV solution, which outputs a cell by genomic bin matrix of (GC and mappability-normalized) read counts. However, your interface only seems to accept BED files as input. How would I go about applying Ginkgo to my matrix?

**Comment by robertaboukhalil** [comment]
Unfortunately, that's not supported, but in principle, you could run some of the code in `process.R`, starting at the [segmentation step](https://github.com/robertaboukhalil/ginkgo/blob/master/scripts/process.R#L187). Hope this helps!

**Comment by vleblanc** [comment]
Hi @pedrofale - I thought I'd chime in here since I've done the same thing you're trying to do (well, sort of). I made individual bam files for each cell using `cellranger-dna bamslice` (it's meant for pulling out groups of cells, but you can make it pull out individual cells easily enough), then made bed files from those and ran them through Ginkgo. I got reasonably similar results from both approaches. Hope this helps!

**Comment by robertaboukhalil** [comment]
Very cool, thanks @vleblanc!

**Comment by pedrofale** [comment]
Thank you, @vleblanc!
